POST http://localhost:3000/register/ 
Content-Type: application/json

{"name": "Raju Mahima",
"mobile": "9908139709", 
"email": "mahima60@gmail.com", 
"password": "mahima@1238", 
"role": "seller" }

###

POST http://localhost:3000/login/
Content-Type: application/json 

{"email": "bhavani34@gmail.com", 
"password": "bhavani@123"}


###

POST http://localhost:3000/property/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZhbmkzNEBnbWFpbC5jb20iLCJpYXQiOjE3MTE1NDU1MTR9.sEqx8TF3DZ_YMGaCf0K9dackMwqcpz4zjazvB8ldd-8

{"location": "hyderabad", 
"cost": 1000000,
"noOfRooms":1,
"status":"available"
}

###

GET http://localhost:3000/property/?location=hyderabad&min_cost=1000000&min_rooms=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZhbmkzNEBnbWFpbC5jb20iLCJpYXQiOjE3MTE1NDU1MTR9.sEqx8TF3DZ_YMGaCf0K9dackMwqcpz4zjazvB8ldd-8



###
GET http://localhost:3000/property/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZhbmkzNEBnbWFpbC5jb20iLCJpYXQiOjE3MTE1NDU1MTR9.sEqx8TF3DZ_YMGaCf0K9dackMwqcpz4zjazvB8ldd-8



###

PUT http://localhost:3000/property/1/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZhbmkzNEBnbWFpbC5jb20iLCJpYXQiOjE3MTE1NDU1MTR9.sEqx8TF3DZ_YMGaCf0K9dackMwqcpz4zjazvB8ldd-8

{"location": "vijayawada"}


###

DELETE http://localhost:3000/property/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZhbmkzNEBnbWFpbC5jb20iLCJpYXQiOjE3MTE1NDU1MTR9.sEqx8TF3DZ_YMGaCf0K9dackMwqcpz4zjazvB8ldd-8
